--JDBreset_store_data.sql
--rp 2014.02.11

UPDATE BCA_INTERNAL_STORE SET QUANTITY=5 WHERE PROD_ID IN ('SKU101', 'SKU102', 'SKU200');
UPDATE BCA_ONLINE_STORE SET QUANTITY=6 WHERE PROD_ID = 'SKU101';
UPDATE BCA_ONLINE_STORE SET QUANTITY=8 WHERE PROD_ID = 'SKU102';
UPDATE BCA_ONLINE_STORE SET QUANTITY=2 WHERE PROD_ID = 'SKU200';
COMMIT;
