--JDBsoademo_drop.sql
--rp 2014.07.09

SPOOL JDBsoademo_drop.log
DROP TABLE BCA_BCA_SHIPTYPES;
DROP TABLE BCA_PRODUCTS;
ALTER TABLE BCA_ITEMS DROP CONSTRAINT ITEMS_ORDERS_FK;
ALTER TABLE BCA_ITEMS DROP CONSTRAINT ITEMS_PRODUCTS_FK;
DROP TABLE BCA_ITEMS;
ALTER TABLE BCA_ORDERS DROP CONSTRAINT ORDERS_CUSTOMERS_FK1;
DROP TABLE BCA_ORDERS;
ALTER TABLE BCA_ADDRESS DROP CONSTRAINT ADDRESS_CUSTOMERS_FK1;
DROP TABLE BCA_ADDRESS;
ALTER TABLE BCA_CREDITCARDS DROP CONSTRAINT CREDITCARDS_CUSTOMERS_FK1;
DROP TABLE BCA_CREDITCARDS;
DROP TABLE BCA_CUSTOMERS;
DROP TABLE BCA_INTERNAL_STORE;
DROP TABLE BCA_ONLINE_STORE;
DROP TABLE BCA_EXTERNAL_STORE;
DROP TABLE BCA_INVENTORY;
DROP TABLE BCA_PRODID_XREFS;

DROP SEQUENCE ORDER_SEQ RESTRICT;
DROP SEQUENCE CUSTOMER_SEQ RESTRICT;
DROP SEQUENCE ADDRESS_SEQ RESTRICT;
DROP SEQUENCE ITEM_SEQ RESTRICT;

SPOOL OFF;
EXIT
